<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
<title>{{ $webinar->title ?? 'Daftar Webinar' }} — PT Eintio Academic & Technology</title>
<style>
:root{--teal:#14b8c4;--teal-dark:#0e9aa8;--navy:#12233f;--ink:#33415c;--muted:#687184;--bg:#f5f8ff;--yellow:#ffd400}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:'Segoe UI',Arial,sans-serif}a{text-decoration:none;color:inherit}button,input,select{font:inherit}.navbar{position:sticky;top:0;z-index:10;background:#fff;border-bottom:1px solid #eef2f5}.nav-inner{max-width:1180px;min-height:58px;margin:auto;padding:0 24px;display:flex;align-items:center;gap:24px}.brand{display:flex;align-items:center;gap:10px;color:var(--navy);font-size:14px;font-weight:800;white-space:nowrap}.brand-mark{color:#f4c900;font-size:16px}.nav-links{display:flex;align-items:center;gap:25px;margin-left:auto}.nav-links a{position:relative;color:#273348;font-size:10px;padding:21px 0 18px}.nav-links a.active{color:var(--teal-dark)}.nav-links a.active:after{content:'';position:absolute;left:0;right:0;bottom:0;height:2px;background:var(--teal-dark)}.btn-teal{background:var(--teal-dark);color:#fff;border-radius:22px;padding:9px 17px!important;font-size:9px!important;font-weight:700}.menu-toggle{display:none;border:0;background:none;font-size:20px;color:var(--navy)}
.webinar-page{min-height:calc(100vh - 58px);padding:48px 24px 70px}.webinar-shell{max-width:1180px;margin:auto}.webinar-grid{display:grid;grid-template-columns:1.4fr .96fr;gap:20px}.webinar-info{min-height:700px;padding:34px;border-radius:18px;background:linear-gradient(135deg,#1598a8,#3aa7b4 45%,#65b8b0);color:#fff;box-shadow:0 15px 35px #12233f22}.webinar-badge{display:inline-flex;padding:5px 13px;border:1px solid #fff;border-radius:20px;font-size:10px;font-weight:800}.webinar-info h1{max-width:650px;margin:22px 0 10px;font-size:31px;line-height:1.2;color:#fff}.webinar-description{max-width:650px;margin:0;color:#ffffffef;font-size:14px;line-height:1.65}.webinar-meta{display:grid;gap:11px;margin:24px 0 34px}.webinar-meta span{display:flex;align-items:center;gap:11px;font-size:12px}.webinar-meta i{width:18px;text-align:center;font-size:15px}.learn-title{margin:0 0 15px;color:#fff;font-size:20px}.learn-list{display:grid;gap:10px;margin:0;padding:0;list-style:none}.learn-list li{display:flex;gap:10px;color:#fff;font-size:12px}.learn-list i{color:var(--yellow);font-size:14px}.webinar-visual{width:100%;height:155px;margin-top:25px;overflow:hidden;border-radius:9px;background:#ffffff20}.webinar-visual img{width:100%;height:100%;object-fit:cover}.visual-placeholder{height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:7px;color:#fffc;font-size:11px}.visual-placeholder i{font-size:30px}
.register-card{align-self:start;padding:28px 27px 25px;border:1px solid #dce3ed;border-radius:18px;background:#fff;box-shadow:0 8px 25px #12233f0a}.register-header{text-align:center;margin-bottom:25px}.register-header h2{margin:0 0 7px;color:var(--navy);font-size:23px}.register-header p{margin:0;color:#667083;font-size:11px;line-height:1.6}.form-group{margin-bottom:17px}.form-label{display:block;margin-bottom:7px;color:#252c39;font-size:11px;font-weight:600}.required{color:#ed4b55}.optional{color:#8a91a0;font-weight:400}.input-wrap{position:relative}.input-icon{position:absolute;left:12px;top:50%;transform:translateY(-50%);color:#7b8496;font-size:14px}.form-control{width:100%;height:38px;padding:0 12px 0 36px;border:1px solid #cbd4e3;border-radius:7px;outline:0;background:#f8faff;color:#30394b;font-size:11px}.form-control:focus{border-color:var(--teal);box-shadow:0 0 0 3px #14b8c41a;background:#fff}select.form-control{appearance:none}.select-arrow{position:absolute;right:12px;top:50%;transform:translateY(-50%);color:#7b8496;font-size:10px}.register-note{display:flex;gap:10px;padding:12px;border-radius:7px;background:#f1fbfc;color:#5d6878;font-size:10px;line-height:1.6;margin:5px 0 20px}.register-note i{color:var(--teal-dark);font-size:15px}.submit-btn{width:100%;height:43px;border:0;border-radius:7px;background:var(--yellow);color:#fff;font-size:12px;font-weight:800;cursor:pointer}.privacy{text-align:center;margin-top:17px;color:#858c99;font-size:9px}.webinar-benefits{display:grid;grid-template-columns:repeat(4,1fr);margin-top:50px;padding:28px 20px;border-radius:18px;background:#fff;box-shadow:0 6px 25px #12233f09}.benefit{text-align:center;padding:0 25px}.benefit+.benefit{border-left:1px solid #e1e7ef}.benefit-icon{width:40px;height:40px;margin:0 auto 12px;display:flex;align-items:center;justify-content:center;border-radius:50%;background:#effafb;color:var(--teal-dark)}.benefit h3{margin:0 0 7px;color:#202938;font-size:12px}.benefit p{max-width:180px;margin:auto;color:#687184;font-size:10px;line-height:1.55}
.site-footer{background:#fff;border-top:1px solid #edf1f5}.footer-inner{max-width:1180px;margin:auto;padding:45px 24px 24px;display:grid;grid-template-columns:1.5fr 1fr 1fr 1.2fr;gap:35px}.footer-title{margin:0 0 13px;color:var(--navy);font-size:12px}.footer-brand{color:var(--navy);font-size:13px;font-weight:800;margin-bottom:9px}.footer-text{max-width:260px;color:#69768a;font-size:9px;line-height:1.7;margin:0}.footer-links{display:grid;gap:8px}.footer-links a,.footer-contact span{color:#68768a;font-size:9px}.footer-contact{display:grid;gap:9px}.footer-contact span{display:flex;gap:8px}.footer-contact i{width:13px;color:var(--teal-dark)}.footer-bottom{max-width:1180px;margin:auto;padding:15px 24px 22px;border-top:1px solid #edf1f5;color:#8a94a4;font-size:8.5px;text-align:center}
@media(max-width:900px){.nav-links{gap:15px}.webinar-grid{grid-template-columns:1fr}.webinar-info{min-height:auto}.webinar-benefits{grid-template-columns:repeat(2,1fr);gap:25px 0}.benefit:nth-child(3){border-left:0}.footer-inner{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.menu-toggle{display:block;margin-left:auto}.nav-links{display:none;position:absolute;left:0;right:0;top:58px;padding:12px 20px 18px;flex-direction:column;align-items:stretch;gap:0;background:#fff;box-shadow:0 10px 20px #12233f14}.nav-links.open{display:flex}.nav-links a{padding:11px 0}.nav-links a.active:after{display:none}.webinar-page{padding:25px 14px 45px}.webinar-info{padding:25px 21px;border-radius:15px}.webinar-info h1{font-size:25px}.webinar-description{font-size:12px}.register-card{padding:24px 20px}.webinar-benefits{grid-template-columns:1fr}.benefit{padding:12px 10px}.benefit+.benefit{border-left:0;border-top:1px solid #e1e7ef}.footer-inner{grid-template-columns:1fr}}
</style>
</head>
<body>
<nav class="navbar"><div class="nav-inner"><a class="brand" href="{{ route('home') }}"><span class="brand-mark">▣</span>PT Eintio Academic &amp; Technology</a><button class="menu-toggle" onclick="toggleMenu()"><i class="fa-solid fa-bars"></i></button><div class="nav-links" id="mainNav"><a href="{{ route('home') }}">Beranda</a><a href="{{ route('profile') }}">Profil</a><a href="{{ route('portfolios') }}">Portofolio</a><a href="{{ route('teams') }}">Tim</a><a class="active" href="{{ route('blog') }}">Blog</a><a href="{{ route('testimoni') }}">Testimoni</a><a href="{{ route('contact') }}">Contact</a><a class="btn-teal" href="https://wa.me/6281234567890" target="_blank">Konsultasi WhatsApp →</a></div></div></nav>
<main class="webinar-page"><div class="webinar-shell"><div class="webinar-grid">
<section class="webinar-info"><span class="webinar-badge">{{ $webinar->badge ?? 'FREE WEBINAR' }}</span><h1>{{ $webinar->title ?? 'AI untuk Produktivitas: Kerja Lebih Cerdas, Hasil Lebih Maksimal' }}</h1><p class="webinar-description">{{ $webinar->description ?? 'Webinar ini akan membahas bagaimana AI dapat membantu meningkatkan produktivitas kerja sehari-hari, mengotomatiskan tugas berulang, dan memberikan wawasan berbasis data untuk pengambilan keputusan yang lebih baik.' }}</p><div class="webinar-meta"><span><i class="fa-regular fa-calendar"></i>{{ $webinar->date_label ?? 'Sabtu, 24 Agustus 2026' }}</span><span><i class="fa-regular fa-clock"></i>{{ $webinar->time_label ?? '10.00 - 12.00 WIB' }}</span><span><i class="fa-solid fa-video"></i>{{ $webinar->platform ?? 'Live on Zoom' }}</span></div><h2 class="learn-title">Apa yang akan Anda pelajari?</h2><ul class="learn-list">@foreach(($webinar->learning_points ?? ['Fundamental AI dalam dunia kerja modern','Tools AI praktis untuk manajemen waktu','Otomatisasi tugas repetitif tanpa coding','Analisis data cepat dengan AI assistants','Etika dan keamanan penggunaan AI di kantor']) as $point)<li><i class="fa-regular fa-circle-check"></i><span>{{ is_array($point) ? ($point['title'] ?? '') : $point }}</span></li>@endforeach</ul><div class="webinar-visual">@if(!empty($webinar->image))<img src="{{ \Illuminate\Support\Facades\Storage::url($webinar->image) }}" alt="{{ $webinar->title }}">@elseif(!empty($webinar->thumbnail))<img src="{{ \Illuminate\Support\Facades\Storage::url($webinar->thumbnail) }}" alt="{{ $webinar->title }}">@else<div class="visual-placeholder"><i class="fa-solid fa-display"></i><span>Preview Webinar</span></div>@endif</div></section>
<section class="register-card"><div class="register-header"><h2>Daftar Webinar</h2><p>Isi formulir di bawah ini untuk mengamankan kursi Anda.</p></div><form method="POST" action="{{ $registerAction ?? '#' }}">@csrf
<div class="form-group"><label class="form-label">Nama Lengkap <span class="required">*</span></label><div class="input-wrap"><i class="input-icon fa-regular fa-user"></i><input class="form-control" name="name" value="{{ old('name') }}" placeholder="John Doe" required></div></div>
<div class="form-group"><label class="form-label">Email <span class="required">*</span></label><div class="input-wrap"><i class="input-icon fa-regular fa-envelope"></i><input class="form-control" type="email" name="email" value="{{ old('email') }}" placeholder="john@example.com" required></div></div>
<div class="form-group"><label class="form-label">Nomor WhatsApp <span class="required">*</span></label><div class="input-wrap"><i class="input-icon fa-solid fa-phone"></i><input class="form-control" type="tel" name="whatsapp" value="{{ old('whatsapp') }}" placeholder="08123456789" required></div></div>
<div class="form-group"><label class="form-label">Instansi / Perusahaan <span class="optional">(Opsional)</span></label><div class="input-wrap"><i class="input-icon fa-regular fa-building"></i><input class="form-control" name="company" value="{{ old('company') }}" placeholder="Nama Perusahaan"></div></div>
<div class="form-group"><label class="form-label">Pekerjaan / Jabatan <span class="required">*</span></label><div class="input-wrap"><i class="input-icon fa-regular fa-id-badge"></i><select class="form-control" name="job" required><option value="">Pilih Jabatan</option><option>Pelajar / Mahasiswa</option><option>Staff</option><option>Supervisor</option><option>Manager</option><option>Owner / Founder</option><option>Lainnya</option></select><i class="select-arrow fa-solid fa-chevron-down"></i></div></div>
<div class="register-note"><i class="fa-regular fa-circle-info"></i><span>Setelah mendaftar, Anda akan menerima email konfirmasi berisi link Zoom dan panduan mengikuti webinar.</span></div><button class="submit-btn" type="submit">Daftar Sekarang <i class="fa-solid fa-arrow-right"></i></button><div class="privacy"><i class="fa-solid fa-lock"></i> Data Anda aman dan tidak akan dibagikan ke pihak ketiga.</div></form></section></div>
<section class="webinar-benefits"><article class="benefit"><div class="benefit-icon"><i class="fa-solid fa-tag"></i></div><h3>100% Gratis</h3><p>Tanpa biaya pendaftaran sedikitpun.</p></article><article class="benefit"><div class="benefit-icon"><i class="fa-regular fa-badge-check"></i></div><h3>E-Certificate</h3><p>Sertifikat resmi untuk peserta aktif.</p></article><article class="benefit"><div class="benefit-icon"><i class="fa-regular fa-comments"></i></div><h3>Live Interactive</h3><p>Sesi Q&amp;A langsung dengan pemateri ahli.</p></article><article class="benefit"><div class="benefit-icon"><i class="fa-regular fa-circle-play"></i></div><h3>Rekaman Webinar</h3><p>Akses ulang materi kapan saja.</p></article></section></div></main>
<footer class="site-footer"><div class="footer-inner"><div><div class="footer-brand">PT Eintio Academic &amp; Technology</div><p class="footer-text">Solusi teknologi, akademik, dan transformasi digital untuk membantu organisasi berkembang lebih efektif.</p></div><div><h3 class="footer-title">Navigasi</h3><div class="footer-links"><a href="{{ route('home') }}">Beranda</a><a href="{{ route('profile') }}">Profil</a><a href="{{ route('portfolios') }}">Portofolio</a><a href="{{ route('teams') }}">Tim</a><a href="{{ route('blog') }}">Blog</a></div></div><div><h3 class="footer-title">Layanan</h3><div class="footer-links"><a href="#">Technology</a><a href="#">Business</a><a href="#">Education</a><a href="#">Academic</a></div></div><div><h3 class="footer-title">Kontak</h3><div class="footer-contact"><span><i class="fa-regular fa-envelope"></i>info@eintio.com</span><span><i class="fa-solid fa-phone"></i>+62 812-3456-7890</span><span><i class="fa-solid fa-location-dot"></i>Indonesia</span></div></div></div><div class="footer-bottom">© {{ date('Y') }} PT Eintio Academic &amp; Technology. All rights reserved.</div></footer>
<script>function toggleMenu(){document.getElementById('mainNav').classList.toggle('open')}</script>
</body></html>
